// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// Account
    /// </summary>
    [Serializable]
    public class Account
    {

        ///<summary>
        /// 编号
        ///</summary>
        public int Id { get; set; } // Id (Primary key)

        ///<summary>
        /// 英文名称
        ///</summary>
        public string EName { get; set; } // EName (length: 50)

        ///<summary>
        /// 状态（系统枚举）
        ///</summary>
        public Status Status { get; set; } // Status
    }

}
// </auto-generated>
