// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// Account
    /// </summary>
    public class AccountMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Account>
    {
        public AccountMap()
            : this("user")
        {
        }

        public AccountMap(string schema)
        {
            ToTable("Account", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.EName).HasColumnName(@"EName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("bigint").IsRequired();
        }
    }

}
// </auto-generated>
