// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// ArrangeCourse
    /// </summary>
    public class ArrangeCourseMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ArrangeCourse>
    {
        public ArrangeCourseMap()
            : this("study")
        {
        }

        public ArrangeCourseMap(string schema)
        {
            ToTable("ArrangeCourse", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CourseId).HasColumnName(@"CourseId").HasColumnType("int").IsOptional();
            Property(x => x.BeginTime).HasColumnName(@"BeginTime").HasColumnType("datetime").IsRequired();
            Property(x => x.CancelStatusType).HasColumnName(@"CancelStatusType").HasColumnType("bigint").IsRequired();
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("bigint").IsRequired();

            // Foreign keys
            HasOptional(a => a.Course).WithMany(b => b.ArrangeCourses).HasForeignKey(c => c.CourseId); // FK_ArrangeCourse_Course
        }
    }

}
// </auto-generated>
