// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// BlacklistCourse
    /// </summary>
    public class BlacklistCourseMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<BlacklistCourse>
    {
        public BlacklistCourseMap()
            : this("stu")
        {
        }

        public BlacklistCourseMap(string schema)
        {
            ToTable("BlacklistCourse", schema);
            HasKey(x => new { x.StudentId, x.CourseId });

            Property(x => x.StudentId).HasColumnName(@"StudentId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CourseId).HasColumnName(@"CourseId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("bigint").IsRequired();
        }
    }

}
// </auto-generated>
