// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// BlacklistUser
    /// </summary>
    public class BlacklistUserMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<BlacklistUser>
    {
        public BlacklistUserMap()
            : this("user")
        {
        }

        public BlacklistUserMap(string schema)
        {
            ToTable("BlacklistUser", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsRequired();
            Property(x => x.BuserId).HasColumnName(@"BuserId").HasColumnType("int").IsRequired();
            Property(x => x.UserType).HasColumnName(@"UserType").HasColumnType("bigint").IsRequired();
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("bigint").IsRequired();
        }
    }

}
// </auto-generated>
