// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// BlacklistCourse
    /// </summary>
    [Serializable]
    public class BlacklistCourse
    {
        public int StudentId { get; set; } // StudentId (Primary key)
        public int CourseId { get; set; } // CourseId (Primary key)
        public Status Status { get; set; } // Status
    }

}
// </auto-generated>
