// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// BookRecord
    /// </summary>
    [Serializable]
    public class BookRecord
    {
        public int ArrangeCourseId { get; set; } // ArrangeCourseId (Primary key)
        public int StudentId { get; set; } // StudentId (Primary key)
        public PassStatusType PassStatusType { get; set; } // PassStatusType
        public bool IsUnBook { get; set; } // IsUnBook
        public Status Status { get; set; } // Status
        public bool IsOwner { get; set; } // IsOwner

        // Foreign keys

        /// <summary>
        /// Parent ArrangeCourse pointed by [BookRecord].([ArrangeCourseId]) (FK_BookRecord_ArrangeCourse)
        /// </summary>
        public virtual ArrangeCourse ArrangeCourse { get; set; } // FK_BookRecord_ArrangeCourse
    }

}
// </auto-generated>
