// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// ClassTypePool
    /// </summary>
    public class ClassTypePoolMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ClassTypePool>
    {
        public ClassTypePoolMap()
            : this("stu")
        {
        }

        public ClassTypePoolMap(string schema)
        {
            ToTable("ClassTypePool", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.StudentId).HasColumnName(@"StudentId").HasColumnType("int").IsRequired();
            Property(x => x.ClassType).HasColumnName(@"ClassType").HasColumnType("bigint").IsRequired();
            Property(x => x.StudentProductPackageId).HasColumnName(@"StudentProductPackageId").HasColumnType("int").IsOptional();
            Property(x => x.IsLimit).HasColumnName(@"IsLimit").HasColumnType("bit").IsRequired();
            Property(x => x.Completed).HasColumnName(@"Completed").HasColumnType("int").IsRequired();
            Property(x => x.Total).HasColumnName(@"Total").HasColumnType("int").IsRequired();
            Property(x => x.ContractStatusType).HasColumnName(@"ContractStatusType").HasColumnType("bigint").IsRequired();
            Property(x => x.BeginDate).HasColumnName(@"BeginDate").HasColumnType("date").IsRequired();
            Property(x => x.EndDate).HasColumnName(@"EndDate").HasColumnType("date").IsRequired();
            Property(x => x.ContractTypeId).HasColumnName(@"ContractTypeId").HasColumnType("int").IsOptional();
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("bigint").IsRequired();
        }
    }

}
// </auto-generated>
