// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// Course
    /// </summary>
    [Serializable]
    public class Course
    {
        public int Id { get; set; } // Id (Primary key)
        public int? CourseSubjectId { get; set; } // CourseSubjectId
        public ClassType? ClassType { get; set; } // ClassType
        public LevelType? LevelType { get; set; } // LevelType
        public CrowdType? CrowdType { get; set; } // CrowdType
        public int OrderNum { get; set; } // OrderNum
        public Status Status { get; set; } // Status
        public string SCName { get; set; } // SCName (length: 32)
        public string SEName { get; set; } // SEName (length: 32)

        // Reverse navigation

        /// <summary>
        /// Child ArrangeCourses where [ArrangeCourse].[CourseId] point to this entity (FK_ArrangeCourse_Course)
        /// </summary>
        public virtual ICollection<ArrangeCourse> ArrangeCourses { get; set; } // ArrangeCourse.FK_ArrangeCourse_Course
        /// <summary>
        /// Child Matchings where [Matching].[CourseId] point to this entity (FK_Matching_Course)
        /// </summary>
        public virtual ICollection<Matching> Matchings { get; set; } // Matching.FK_Matching_Course
        /// <summary>
        /// Child StudentProductPackageCourses where [StudentProductPackageCourse].[CourseId] point to this entity (FK_StudentProductPackageCourse_Course)
        /// </summary>
        public virtual ICollection<StudentProductPackageCourse> StudentProductPackageCourses { get; set; } // StudentProductPackageCourse.FK_StudentProductPackageCourse_Course

        // Foreign keys

        /// <summary>
        /// Parent CourseSubject pointed by [Course].([CourseSubjectId]) (FK_Course_CourseSubject)
        /// </summary>
        public virtual CourseSubject CourseSubject { get; set; } // FK_Course_CourseSubject

        public Course()
        {
            ArrangeCourses = new List<ArrangeCourse>();
            Matchings = new List<Matching>();
            StudentProductPackageCourses = new List<StudentProductPackageCourse>();
        }
    }

}
// </auto-generated>
