// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// Course
    /// </summary>
    public class CourseMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Course>
    {
        public CourseMap()
            : this("curriculum")
        {
        }

        public CourseMap(string schema)
        {
            ToTable("Course", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CourseSubjectId).HasColumnName(@"CourseSubjectId").HasColumnType("int").IsOptional();
            Property(x => x.ClassType).HasColumnName(@"ClassType").HasColumnType("bigint").IsOptional();
            Property(x => x.LevelType).HasColumnName(@"LevelType").HasColumnType("bigint").IsOptional();
            Property(x => x.CrowdType).HasColumnName(@"CrowdType").HasColumnType("bigint").IsOptional();
            Property(x => x.OrderNum).HasColumnName(@"OrderNum").HasColumnType("int").IsRequired();
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("bigint").IsRequired();
            Property(x => x.SCName).HasColumnName(@"SCName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(32);
            Property(x => x.SEName).HasColumnName(@"SEName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(32);

            // Foreign keys
            HasOptional(a => a.CourseSubject).WithMany(b => b.Courses).HasForeignKey(c => c.CourseSubjectId).WillCascadeOnDelete(false); // FK_Course_CourseSubject
        }
    }

}
// </auto-generated>
