// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// CourseSubject
    /// </summary>
    [Serializable]
    public class CourseSubject
    {
        public int Id { get; set; } // Id (Primary key)
        public string CName { get; set; } // CName (length: 100)
        public string EName { get; set; } // EName (length: 50)
        public int OrderNum { get; set; } // OrderNum
        public Status Status { get; set; } // Status

        // Reverse navigation

        /// <summary>
        /// Child Courses where [Course].[CourseSubjectId] point to this entity (FK_Course_CourseSubject)
        /// </summary>
        public virtual ICollection<Course> Courses { get; set; } // Course.FK_Course_CourseSubject
        /// <summary>
        /// Child CourseTypeSubjects where [CourseTypeSubject].[CourseSubjectId] point to this entity (FK_CourseTypeSubject_CourseSubject)
        /// </summary>
        public virtual ICollection<CourseTypeSubject> CourseTypeSubjects { get; set; } // CourseTypeSubject.FK_CourseTypeSubject_CourseSubject

        public CourseSubject()
        {
            Courses = new List<Course>();
            CourseTypeSubjects = new List<CourseTypeSubject>();
        }
    }

}
// </auto-generated>
