// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// CourseType
    /// </summary>
    [Serializable]
    public class CourseType
    {
        public int Id { get; set; } // Id (Primary key)
        public string CName { get; set; } // CName (length: 200)
        public string EName { get; set; } // EName (length: 100)
        public Status Status { get; set; } // Status
        public int? CourseAreaTypeId { get; set; } // CourseAreaTypeId

        // Reverse navigation

        /// <summary>
        /// Child CourseTypeSubjects where [CourseTypeSubject].[CourseTypeId] point to this entity (FK_CourseTypeSubject_CourseType)
        /// </summary>
        public virtual ICollection<CourseTypeSubject> CourseTypeSubjects { get; set; } // CourseTypeSubject.FK_CourseTypeSubject_CourseType
        /// <summary>
        /// Child UserCourseTypes where [UserCourseType].[CourseTypeId] point to this entity (FK_UserCourseType_CourseType)
        /// </summary>
        public virtual ICollection<UserCourseType> UserCourseTypes { get; set; } // UserCourseType.FK_UserCourseType_CourseType

        public CourseType()
        {
            CourseTypeSubjects = new List<CourseTypeSubject>();
            UserCourseTypes = new List<UserCourseType>();
        }
    }

}
// </auto-generated>
