// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// CourseType
    /// </summary>
    public class CourseTypeMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CourseType>
    {
        public CourseTypeMap()
            : this("curriculum")
        {
        }

        public CourseTypeMap(string schema)
        {
            ToTable("CourseType", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CName).HasColumnName(@"CName").HasColumnType("nvarchar").IsRequired().HasMaxLength(200);
            Property(x => x.EName).HasColumnName(@"EName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(100);
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("bigint").IsRequired();
            Property(x => x.CourseAreaTypeId).HasColumnName(@"CourseAreaTypeId").HasColumnType("int").IsOptional();
        }
    }

}
// </auto-generated>
