// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// CourseSubject
    /// </summary>
    public class CourseSubjectMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CourseSubject>
    {
        public CourseSubjectMap()
            : this("curriculum")
        {
        }

        public CourseSubjectMap(string schema)
        {
            ToTable("CourseSubject", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CName).HasColumnName(@"CName").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.EName).HasColumnName(@"EName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.OrderNum).HasColumnName(@"OrderNum").HasColumnType("int").IsRequired();
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("bigint").IsRequired();
        }
    }

}
// </auto-generated>
