// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// CourseTypeSubject
    /// </summary>
    public class CourseTypeSubjectMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CourseTypeSubject>
    {
        public CourseTypeSubjectMap()
            : this("curriculum")
        {
        }

        public CourseTypeSubjectMap(string schema)
        {
            ToTable("CourseTypeSubject", schema);
            HasKey(x => new { x.CourseTypeId, x.CourseSubjectId });

            Property(x => x.CourseTypeId).HasColumnName(@"CourseTypeId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CourseSubjectId).HasColumnName(@"CourseSubjectId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("bigint").IsRequired();

            // Foreign keys
            HasRequired(a => a.CourseSubject).WithMany(b => b.CourseTypeSubjects).HasForeignKey(c => c.CourseSubjectId).WillCascadeOnDelete(false); // FK_CourseTypeSubject_CourseSubject
            HasRequired(a => a.CourseType).WithMany(b => b.CourseTypeSubjects).HasForeignKey(c => c.CourseTypeId).WillCascadeOnDelete(false); // FK_CourseTypeSubject_CourseType
        }
    }

}
// </auto-generated>
