// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// Exclusiver
    /// </summary>
    [Serializable]
    public class Exclusiver
    {
        public int Id { get; set; } // Id (Primary key)
        public int UserId { get; set; } // UserId
        public UserType UserType { get; set; } // UserType
        public int ExclusiveBy { get; set; } // ExclusiveBy
        public Status Status { get; set; } // Status
        public ProductType? ProductType { get; set; } // ProductType
    }

}
// </auto-generated>
