// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// Favorite
    /// </summary>
    [Serializable]
    public class Favorite
    {
        public int Id { get; set; } // Id (Primary key)
        public int UserId { get; set; } // UserId
        public int FuserId { get; set; } // FuserId
        public UserType UserType { get; set; } // UserType
        public Status Status { get; set; } // Status
        public int? UpdateBy { get; set; } // UpdateBy
        public DateTime? UpdateTime { get; set; } // UpdateTime
        public int? CreateBy { get; set; } // CreateBy
        public DateTime CreateTime { get; set; } // CreateTime
        public string Remark { get; set; } // Remark (length: 100)
    }

}
// </auto-generated>
