// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// History
    /// </summary>
    public class HistoryMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<History>
    {
        public HistoryMap()
            : this("dbo")
        {
        }

        public HistoryMap(string schema)
        {
            ToTable("History", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.MathchingId).HasColumnName(@"MathchingId").HasColumnType("int").IsOptional();
            Property(x => x.LevelType).HasColumnName(@"LevelType").HasColumnType("bigint").IsOptional();
            Property(x => x.ClassType).HasColumnName(@"ClassType").HasColumnType("bigint").IsRequired();
            Property(x => x.CurrStudent).HasColumnName(@"CurrStudent").HasColumnType("int").IsRequired();
            Property(x => x.MaxStudent).HasColumnName(@"MaxStudent").HasColumnType("int").IsRequired();
            Property(x => x.BeginTime).HasColumnName(@"BeginTime").HasColumnType("datetime").IsRequired();
            Property(x => x.EndTime).HasColumnName(@"EndTime").HasColumnType("datetime").IsRequired();
            Property(x => x.CourseId).HasColumnName(@"CourseId").HasColumnType("int").IsOptional();
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("bigint").IsRequired();
            Property(x => x.CreateTime).HasColumnName(@"CreateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.Remark).HasColumnName(@"Remark").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
        }
    }

}
// </auto-generated>
