// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// HistoryStu
    /// </summary>
    public class HistoryStuMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<HistoryStu>
    {
        public HistoryStuMap()
            : this("dbo")
        {
        }

        public HistoryStuMap(string schema)
        {
            ToTable("HistoryStu", schema);
            HasKey(x => new { x.HistoryId, x.StudentId });

            Property(x => x.HistoryId).HasColumnName(@"HistoryId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.StudentId).HasColumnName(@"StudentId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.LevelType).HasColumnName(@"LevelType").HasColumnType("bigint").IsOptional();
            Property(x => x.ClassType).HasColumnName(@"ClassType").HasColumnType("bigint").IsRequired();
            Property(x => x.BeginTime).HasColumnName(@"BeginTime").HasColumnType("datetime").IsRequired();
            Property(x => x.EndTime).HasColumnName(@"EndTime").HasColumnType("datetime").IsRequired();
            Property(x => x.CrowdType).HasColumnName(@"CrowdType").HasColumnType("bigint").IsOptional();
            Property(x => x.CustomTeacherId).HasColumnName(@"CustomTeacherId").HasColumnType("int").IsOptional();
            Property(x => x.CustomPackageId).HasColumnName(@"CustomPackageId").HasColumnType("int").IsOptional();
            Property(x => x.CustomCourseId).HasColumnName(@"CustomCourseId").HasColumnType("int").IsOptional();
            Property(x => x.PlatformType).HasColumnName(@"PlatformType").HasColumnType("bigint").IsRequired();
            Property(x => x.CreateBy).HasColumnName(@"CreateBy").HasColumnType("int").IsRequired();
            Property(x => x.CreateTime).HasColumnName(@"CreateTime").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.History).WithMany(b => b.HistoryStus).HasForeignKey(c => c.HistoryId); // FK_HistoryStu_History
        }
    }

}
// </auto-generated>
