// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// History
    /// </summary>
    [Serializable]
    public class History
    {
        public int Id { get; set; } // Id (Primary key)

        ///<summary>
        /// 编号
        ///</summary>
        public int? MathchingId { get; set; } // MathchingId

        ///<summary>
        /// 匹配的级别（系统枚举）
        ///</summary>
        public LevelType? LevelType { get; set; } // LevelType

        ///<summary>
        /// 课堂类型（系统枚举）
        ///</summary>
        public ClassType ClassType { get; set; } // ClassType

        ///<summary>
        /// 当前学员人数
        ///</summary>
        public int CurrStudent { get; set; } // CurrStudent

        ///<summary>
        /// 最大学员人数
        ///</summary>
        public int MaxStudent { get; set; } // MaxStudent

        ///<summary>
        /// 课程开始时间
        ///</summary>
        public DateTime BeginTime { get; set; } // BeginTime

        ///<summary>
        /// 课程结束时间
        ///</summary>
        public DateTime EndTime { get; set; } // EndTime

        ///<summary>
        /// 课程编号（完成匹配之后标记）
        ///</summary>
        public int? CourseId { get; set; } // CourseId

        ///<summary>
        /// 状态（系统枚举）
        ///</summary>
        public Status Status { get; set; } // Status

        ///<summary>
        /// 创建时间
        ///</summary>
        public DateTime? CreateTime { get; set; } // CreateTime

        ///<summary>
        /// 备注
        ///</summary>
        public string Remark { get; set; } // Remark (length: 100)

        // Reverse navigation

        /// <summary>
        /// Child HistoryStus where [HistoryStu].[HistoryId] point to this entity (FK_HistoryStu_History)
        /// </summary>
        public virtual ICollection<HistoryStu> HistoryStus { get; set; } // HistoryStu.FK_HistoryStu_History
        /// <summary>
        /// Child HistoryTeas where [HistoryTea].[HistoryId] point to this entity (FK_HistoryTea_History)
        /// </summary>
        public virtual ICollection<HistoryTea> HistoryTeas { get; set; } // HistoryTea.FK_HistoryTea_History

        public History()
        {
            HistoryStus = new List<HistoryStu>();
            HistoryTeas = new List<HistoryTea>();
        }
    }

}
// </auto-generated>
