// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// HistoryTea
    /// </summary>
    [Serializable]
    public class HistoryTea
    {
        public int HistoryId { get; set; } // HistoryId (Primary key)
        public int TeacherId { get; set; } // TeacherId (Primary key)
        public LevelType LevelType { get; set; } // LevelType
        public ClassType ClassType { get; set; } // ClassType

        ///<summary>
        /// 课程开始时间
        ///</summary>
        public DateTime BeginTime { get; set; } // BeginTime

        ///<summary>
        /// 课程结束时间
        ///</summary>
        public DateTime EndTime { get; set; } // EndTime
        public int MathingStatus { get; set; } // MathingStatus

        ///<summary>
        /// 创建时间
        ///</summary>
        public DateTime? CreateTime { get; set; } // CreateTime

        // Foreign keys

        /// <summary>
        /// Parent History pointed by [HistoryTea].([HistoryId]) (FK_HistoryTea_History)
        /// </summary>
        public virtual History History { get; set; } // FK_HistoryTea_History
    }

}
// </auto-generated>
