// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// HistoryTea
    /// </summary>
    public class HistoryTeaMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<HistoryTea>
    {
        public HistoryTeaMap()
            : this("dbo")
        {
        }

        public HistoryTeaMap(string schema)
        {
            ToTable("HistoryTea", schema);
            HasKey(x => new { x.HistoryId, x.TeacherId });

            Property(x => x.HistoryId).HasColumnName(@"HistoryId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.TeacherId).HasColumnName(@"TeacherId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.LevelType).HasColumnName(@"LevelType").HasColumnType("bigint").IsRequired();
            Property(x => x.ClassType).HasColumnName(@"ClassType").HasColumnType("bigint").IsRequired();
            Property(x => x.BeginTime).HasColumnName(@"BeginTime").HasColumnType("datetime").IsRequired();
            Property(x => x.EndTime).HasColumnName(@"EndTime").HasColumnType("datetime").IsRequired();
            Property(x => x.MathingStatus).HasColumnName(@"MathingStatus").HasColumnType("int").IsRequired();
            Property(x => x.CreateTime).HasColumnName(@"CreateTime").HasColumnType("datetime").IsOptional();

            // Foreign keys
            HasRequired(a => a.History).WithMany(b => b.HistoryTeas).HasForeignKey(c => c.HistoryId); // FK_HistoryTea_History
        }
    }

}
// </auto-generated>
