// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// HistoryStu
    /// </summary>
    [Serializable]
    public class HistoryStu
    {
        public int HistoryId { get; set; } // HistoryId (Primary key)
        public int StudentId { get; set; } // StudentId (Primary key)

        ///<summary>
        /// 当前级别（系统枚举）
        ///</summary>
        public LevelType? LevelType { get; set; } // LevelType

        ///<summary>
        /// 课堂类型（系统枚举）
        ///</summary>
        public ClassType ClassType { get; set; } // ClassType

        ///<summary>
        /// 课程开始时间
        ///</summary>
        public DateTime BeginTime { get; set; } // BeginTime

        ///<summary>
        /// 课程结束时间
        ///</summary>
        public DateTime EndTime { get; set; } // EndTime

        ///<summary>
        /// 学员人群分类
        ///</summary>
        public CrowdType? CrowdType { get; set; } // CrowdType

        ///<summary>
        /// 定制教师Id
        ///</summary>
        public int? CustomTeacherId { get; set; } // CustomTeacherId

        ///<summary>
        /// 定制产品包Id
        ///</summary>
        public int? CustomPackageId { get; set; } // CustomPackageId

        ///<summary>
        /// 定制课程Id
        ///</summary>
        public int? CustomCourseId { get; set; } // CustomCourseId
        public PlatformType PlatformType { get; set; } // PlatformType

        ///<summary>
        /// 订课人
        ///</summary>
        public int CreateBy { get; set; } // CreateBy

        ///<summary>
        /// 创建时间
        ///</summary>
        public DateTime CreateTime { get; set; } // CreateTime

        // Foreign keys

        /// <summary>
        /// Parent History pointed by [HistoryStu].([HistoryId]) (FK_HistoryStu_History)
        /// </summary>
        public virtual History History { get; set; } // FK_HistoryStu_History
    }

}
// </auto-generated>
