// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// Matching
    /// </summary>
    public class MatchingMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Matching>
    {
        public MatchingMap()
            : this("dbo")
        {
        }

        public MatchingMap(string schema)
        {
            ToTable("Matching", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.LevelType).HasColumnName(@"LevelType").HasColumnType("bigint").IsRequired();
            Property(x => x.ClassType).HasColumnName(@"ClassType").HasColumnType("bigint").IsRequired();
            Property(x => x.CurrStuCount).HasColumnName(@"CurrStuCount").HasColumnType("tinyint").IsRequired();
            Property(x => x.BeginTime).HasColumnName(@"BeginTime").HasColumnType("datetime").IsRequired();
            Property(x => x.EndTime).HasColumnName(@"EndTime").HasColumnType("datetime").IsRequired();
            Property(x => x.CourseId).HasColumnName(@"CourseId").HasColumnType("int").IsRequired();
            Property(x => x.IsCustomCourse).HasColumnName(@"IsCustomCourse").HasColumnType("bit").IsRequired();
            Property(x => x.IsCustomTeacher).HasColumnName(@"IsCustomTeacher").HasColumnType("bit").IsRequired();
            Property(x => x.PublishFailCount).HasColumnName(@"PublishFailCount").HasColumnType("int").IsRequired();
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("bigint").IsRequired();
            Property(x => x.UpdateBy).HasColumnName(@"UpdateBy").HasColumnType("int").IsOptional();
            Property(x => x.UpdateTime).HasColumnName(@"UpdateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.CreateBy).HasColumnName(@"CreateBy").HasColumnType("int").IsOptional();
            Property(x => x.CreateTime).HasColumnName(@"CreateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.Remark).HasColumnName(@"Remark").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.RowVersion).HasColumnName(@"RowVersion").HasColumnType("timestamp").IsRequired().IsFixedLength().HasMaxLength(8).IsRowVersion();
            Property(x => x.IsOpen).HasColumnName(@"IsOpen").HasColumnType("bit").IsRequired();
            Property(x => x.IsBatch).HasColumnName(@"IsBatch").HasColumnType("bit").IsRequired();
            Property(x => x.BatchLeadStudentId).HasColumnName(@"BatchLeadStudentId").HasColumnType("int").IsOptional();
            Property(x => x.BatchMaxBookNum).HasColumnName(@"BatchMaxBookNum").HasColumnType("int").IsOptional();

            // Foreign keys
            HasRequired(a => a.Course).WithMany(b => b.Matchings).HasForeignKey(c => c.CourseId); // FK_Matching_Course
        }
    }

}
// </auto-generated>
