// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// Matching
    /// </summary>
    [Serializable]
    public class Matching
    {

        ///<summary>
        /// 编号
        ///</summary>
        public int Id { get; set; } // Id (Primary key)

        ///<summary>
        /// 级别类型（教师学员交集）
        ///</summary>
        public LevelType LevelType { get; set; } // LevelType

        ///<summary>
        /// 课堂类型（系统枚举）
        ///</summary>
        public ClassType ClassType { get; set; } // ClassType

        ///<summary>
        /// 当前学员人数
        ///</summary>
        public byte CurrStuCount { get; set; } // CurrStuCount

        ///<summary>
        /// 课程开始时间
        ///</summary>
        public DateTime BeginTime { get; set; } // BeginTime

        ///<summary>
        /// 课程结束时间
        ///</summary>
        public DateTime EndTime { get; set; } // EndTime

        ///<summary>
        /// 课程编号（完成匹配之后标记）
        ///</summary>
        public int CourseId { get; set; } // CourseId

        ///<summary>
        /// 是否定制课程
        ///</summary>
        public bool IsCustomCourse { get; set; } // IsCustomCourse

        ///<summary>
        /// 是否定制教师
        ///</summary>
        public bool IsCustomTeacher { get; set; } // IsCustomTeacher

        ///<summary>
        /// 发布课程失败次数
        ///</summary>
        public int PublishFailCount { get; set; } // PublishFailCount

        ///<summary>
        /// 状态（系统枚举）
        ///</summary>
        public Status Status { get; set; } // Status

        ///<summary>
        /// 更新人
        ///</summary>
        public int? UpdateBy { get; set; } // UpdateBy

        ///<summary>
        /// 更新时间
        ///</summary>
        public DateTime? UpdateTime { get; set; } // UpdateTime

        ///<summary>
        /// 创建人
        ///</summary>
        public int? CreateBy { get; set; } // CreateBy

        ///<summary>
        /// 创建时间
        ///</summary>
        public DateTime? CreateTime { get; set; } // CreateTime

        ///<summary>
        /// 备注
        ///</summary>
        public string Remark { get; set; } // Remark (length: 100)
        public byte[] RowVersion { get; set; } // RowVersion (length: 8)
        public bool IsOpen { get; set; } // IsOpen

        ///<summary>
        /// 是否批量订课(企培)
        ///</summary>
        public bool IsBatch { get; set; } // IsBatch

        ///<summary>
        /// 批量订课代表学员的学员Id
        ///</summary>
        public int? BatchLeadStudentId { get; set; } // BatchLeadStudentId
        public int? BatchMaxBookNum { get; set; } // BatchMaxBookNum

        // Reverse navigation

        /// <summary>
        /// Child MathingCourseTypes where [MathingCourseType].[MathingId] point to this entity (FK_MathingCourseType_Matching)
        /// </summary>
        public virtual ICollection<MathingCourseType> MathingCourseTypes { get; set; } // MathingCourseType.FK_MathingCourseType_Matching
        /// <summary>
        /// Child StuReqs where [StuReq].[MathingId] point to this entity (FK_StuReq_Matching)
        /// </summary>
        public virtual ICollection<StuReq> StuReqs { get; set; } // StuReq.FK_StuReq_Matching
        /// <summary>
        /// Child TeaReqMathings where [TeaReqMathing].[MathingId] point to this entity (FK_TeaReqMathing_Matching)
        /// </summary>
        public virtual ICollection<TeaReqMathing> TeaReqMathings { get; set; } // TeaReqMathing.FK_TeaReqMathing_Matching

        // Foreign keys

        /// <summary>
        /// Parent Course pointed by [Matching].([CourseId]) (FK_Matching_Course)
        /// </summary>
        public virtual Course Course { get; set; } // FK_Matching_Course

        public Matching()
        {
            MathingCourseTypes = new List<MathingCourseType>();
            StuReqs = new List<StuReq>();
            TeaReqMathings = new List<TeaReqMathing>();
        }
    }

}
// </auto-generated>
