// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// MathingCourseType
    /// </summary>
    ///<summary>
    /// 教师学员CourseType交集
    ///</summary>
    [Serializable]
    public class MathingCourseType
    {
        public int Id { get; set; } // Id (Primary key)
        public int MathingId { get; set; } // MathingId
        public int CourseTypeId { get; set; } // CourseTypeId

        // Foreign keys

        /// <summary>
        /// Parent Matching pointed by [MathingCourseType].([MathingId]) (FK_MathingCourseType_Matching)
        /// </summary>
        public virtual Matching Matching { get; set; } // FK_MathingCourseType_Matching
    }

}
// </auto-generated>
