// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// MathingCourseType
    /// </summary>
    public class MathingCourseTypeMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MathingCourseType>
    {
        public MathingCourseTypeMap()
            : this("dbo")
        {
        }

        public MathingCourseTypeMap(string schema)
        {
            ToTable("MathingCourseType", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.MathingId).HasColumnName(@"MathingId").HasColumnType("int").IsRequired();
            Property(x => x.CourseTypeId).HasColumnName(@"CourseTypeId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.Matching).WithMany(b => b.MathingCourseTypes).HasForeignKey(c => c.MathingId); // FK_MathingCourseType_Matching
        }
    }

}
// </auto-generated>
