// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// StudentProductPackageCourse
    /// </summary>
    [Serializable]
    public class StudentProductPackageCourse
    {
        public int Id { get; set; } // Id (Primary key)
        public int StudentProductPackageId { get; set; } // StudentProductPackageId
        public int CourseId { get; set; } // CourseId
        public bool IsComplete { get; set; } // IsComplete
        public int OrderNum { get; set; } // OrderNum
        public Status Status { get; set; } // Status

        // Foreign keys

        /// <summary>
        /// Parent Course pointed by [StudentProductPackageCourse].([CourseId]) (FK_StudentProductPackageCourse_Course)
        /// </summary>
        public virtual Course Course { get; set; } // FK_StudentProductPackageCourse_Course

        /// <summary>
        /// Parent StudentProductPackage pointed by [StudentProductPackageCourse].([StudentProductPackageId]) (FK_StudentProductPackageCourse_StudentProductPackage)
        /// </summary>
        public virtual StudentProductPackage StudentProductPackage { get; set; } // FK_StudentProductPackageCourse_StudentProductPackage
    }

}
// </auto-generated>
