// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// StudentProduct
    /// </summary>
    [Serializable]
    public class StudentProduct
    {
        public int Id { get; set; } // Id (Primary key)
        public int StudentId { get; set; } // StudentId
        public int ProductId { get; set; } // ProductId
        public bool IsPackageSerial { get; set; } // IsPackageSerial
        public bool IsComplete { get; set; } // IsComplete
        public int OrderNum { get; set; } // OrderNum
        public Status Status { get; set; } // Status

        // Reverse navigation

        /// <summary>
        /// Child StudentProductPackages where [StudentProductPackage].[StudentProductId] point to this entity (FK_StudentProductPackage_StudentProduct)
        /// </summary>
        public virtual ICollection<StudentProductPackage> StudentProductPackages { get; set; } // StudentProductPackage.FK_StudentProductPackage_StudentProduct

        public StudentProduct()
        {
            StudentProductPackages = new List<StudentProductPackage>();
        }
    }

}
// </auto-generated>
