// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// StuReq
    /// </summary>
    [Serializable]
    public class StuReq
    {

        ///<summary>
        /// 编号
        ///</summary>
        public int Id { get; set; } // Id (Primary key)

        ///<summary>
        /// 学员编号
        ///</summary>
        public int StudentId { get; set; } // StudentId

        ///<summary>
        /// 当前级别（系统枚举）
        ///</summary>
        public LevelType LevelType { get; set; } // LevelType

        ///<summary>
        /// 课堂类型（系统枚举）
        ///</summary>
        public ClassType ClassType { get; set; } // ClassType

        ///<summary>
        /// 课程开始时间
        ///</summary>
        public DateTime BeginTime { get; set; } // BeginTime

        ///<summary>
        /// 课程结束时间
        ///</summary>
        public DateTime EndTime { get; set; } // EndTime

        ///<summary>
        /// 放课时间 Null不放课  非Null出课时按指定时间放课
        ///</summary>
        public DateTime? OpenTime { get; set; } // OpenTime

        ///<summary>
        /// 学员人群分类
        ///</summary>
        public CrowdType? CrowdType { get; set; } // CrowdType

        ///<summary>
        /// 定制教师Id
        ///</summary>
        public int? CustomTeacherId { get; set; } // CustomTeacherId

        ///<summary>
        /// 定制产品包Id
        ///</summary>
        public int? CustomPackageId { get; set; } // CustomPackageId

        ///<summary>
        /// 定制课程Id
        ///</summary>
        public int? CustomCourseId { get; set; } // CustomCourseId

        ///<summary>
        /// 课程主题编号
        ///</summary>
        public int? CustomCourseSubjectId { get; set; } // CustomCourseSubjectId
        public PlatformType PlatformType { get; set; } // PlatformType

        ///<summary>
        /// 匹配队列Id
        ///</summary>
        public int? MathingId { get; set; } // MathingId

        ///<summary>
        /// 状态（系统枚举）
        ///</summary>
        public Status Status { get; set; } // Status

        ///<summary>
        /// 更新人
        ///</summary>
        public int? UpdateBy { get; set; } // UpdateBy

        ///<summary>
        /// 更新时间
        ///</summary>
        public DateTime? UpdateTime { get; set; } // UpdateTime

        ///<summary>
        /// 订课人
        ///</summary>
        public int CreateBy { get; set; } // CreateBy

        ///<summary>
        /// 创建时间
        ///</summary>
        public DateTime CreateTime { get; set; } // CreateTime

        ///<summary>
        /// 备注
        ///</summary>
        public string Remark { get; set; } // Remark (length: 100)

        // Foreign keys

        /// <summary>
        /// Parent Matching pointed by [StuReq].([MathingId]) (FK_StuReq_Matching)
        /// </summary>
        public virtual Matching Matching { get; set; } // FK_StuReq_Matching
    }

}
// </auto-generated>
