// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// TeachRecord
    /// </summary>
    [Serializable]
    public class TeachRecord
    {
        public int ArrangeCourseId { get; set; } // ArrangeCourseId (Primary key)
        public int TeacherId { get; set; } // TeacherId (Primary key)
        public Status Status { get; set; } // Status
        public int? CancelingBy { get; set; } // CancelingBy
        public CancelStatusType CancelStatusType { get; set; } // CancelStatusType
        public string CancelingReason { get; set; } // CancelingReason (length: 500)
        public int? CanceledBy { get; set; } // CanceledBy
        public string CanceledReason { get; set; } // CanceledReason (length: 500)
        public DateTime? CancelingTime { get; set; } // CancelingTime
        public DateTime? CanceledTime { get; set; } // CanceledTime

        // Foreign keys

        /// <summary>
        /// Parent ArrangeCourse pointed by [TeachRecord].([ArrangeCourseId]) (FK_TeachRecord_ArrangeCourse)
        /// </summary>
        public virtual ArrangeCourse ArrangeCourse { get; set; } // FK_TeachRecord_ArrangeCourse

        /// <summary>
        /// Parent Teacher pointed by [TeachRecord].([TeacherId]) (FK_TeachRecord_Teacher)
        /// </summary>
        public virtual Teacher Teacher { get; set; } // FK_TeachRecord_Teacher
    }

}
// </auto-generated>
