// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// Teacher
    /// </summary>
    public class TeacherMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Teacher>
    {
        public TeacherMap()
            : this("tea")
        {
        }

        public TeacherMap(string schema)
        {
            ToTable("Teacher", schema);
            HasKey(x => x.TeacherId);

            Property(x => x.TeacherId).HasColumnName(@"TeacherId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.TeacherType).HasColumnName(@"TeacherType").HasColumnType("bigint").IsRequired();
            Property(x => x.TeacherStageType).HasColumnName(@"TeacherStageType").HasColumnType("bigint").IsRequired();
            Property(x => x.TeacherJobType).HasColumnName(@"TeacherJobType").HasColumnType("bigint").IsRequired();
            Property(x => x.QualificationType).HasColumnName(@"QualificationType").HasColumnType("bigint").IsOptional();
            Property(x => x.LevelType).HasColumnName(@"LevelType").HasColumnType("bigint").IsOptional();
            Property(x => x.ClassType).HasColumnName(@"ClassType").HasColumnType("bigint").IsOptional();
            Property(x => x.IntroVideo).HasColumnName(@"IntroVideo").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.IntroVoice).HasColumnName(@"IntroVoice").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.RefereeTime).HasColumnName(@"RefereeTime").HasColumnType("datetime").IsOptional();
            Property(x => x.IntroPhoto).HasColumnName(@"IntroPhoto").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("bigint").IsRequired();
        }
    }

}
// </auto-generated>
