// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// Teacher
    /// </summary>
    [Serializable]
    public class Teacher
    {
        public int TeacherId { get; set; } // TeacherId (Primary key)
        public TeacherType TeacherType { get; set; } // TeacherType
        public TeacherStageType TeacherStageType { get; set; } // TeacherStageType
        public TeacherJobType TeacherJobType { get; set; } // TeacherJobType
        public QualificationType? QualificationType { get; set; } // QualificationType
        public LevelType? LevelType { get; set; } // LevelType
        public ClassType? ClassType { get; set; } // ClassType
        public string IntroVideo { get; set; } // IntroVideo (length: 100)
        public string IntroVoice { get; set; } // IntroVoice (length: 100)
        public DateTime? RefereeTime { get; set; } // RefereeTime
        public string IntroPhoto { get; set; } // IntroPhoto (length: 100)

        ///<summary>
        /// 状态（系统枚举）
        ///</summary>
        public Status Status { get; set; } // Status

        // Reverse navigation

        /// <summary>
        /// Child TeachRecords where [TeachRecord].[TeacherId] point to this entity (FK_TeachRecord_Teacher)
        /// </summary>
        public virtual ICollection<TeachRecord> TeachRecords { get; set; } // TeachRecord.FK_TeachRecord_Teacher

        public Teacher()
        {
            TeachRecords = new List<TeachRecord>();
        }
    }

}
// </auto-generated>
