// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// TeacherContract
    /// </summary>
    [Serializable]
    public class TeacherContract
    {

        ///<summary>
        /// 教师编号
        ///</summary>
        public int TeacherId { get; set; } // TeacherId (Primary key)

        ///<summary>
        /// 合同状态（系统枚举）；默认：执行
        ///</summary>
        public ContractStatusType ContractStatusType { get; set; } // ContractStatusType

        ///<summary>
        /// 状态（系统枚举）
        ///</summary>
        public Status Status { get; set; } // Status
    }

}
// </auto-generated>
