// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// TeacherContract
    /// </summary>
    public class TeacherContractMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TeacherContract>
    {
        public TeacherContractMap()
            : this("contract")
        {
        }

        public TeacherContractMap(string schema)
        {
            ToTable("TeacherContract", schema);
            HasKey(x => x.TeacherId);

            Property(x => x.TeacherId).HasColumnName(@"TeacherId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ContractStatusType).HasColumnName(@"ContractStatusType").HasColumnType("bigint").IsRequired();
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("bigint").IsRequired();
        }
    }

}
// </auto-generated>
