// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// TeaReqMathing
    /// </summary>
    [Serializable]
    public class TeaReqMathing
    {
        public int Id { get; set; } // Id (Primary key)
        public int TeaReqId { get; set; } // TeaReqId
        public int MathingId { get; set; } // MathingId

        // Foreign keys

        /// <summary>
        /// Parent Matching pointed by [TeaReqMathing].([MathingId]) (FK_TeaReqMathing_Matching)
        /// </summary>
        public virtual Matching Matching { get; set; } // FK_TeaReqMathing_Matching

        /// <summary>
        /// Parent TeaReq pointed by [TeaReqMathing].([TeaReqId]) (FK_TeaReqMathing_TeaReq)
        /// </summary>
        public virtual TeaReq TeaReq { get; set; } // FK_TeaReqMathing_TeaReq
    }

}
// </auto-generated>
