// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// UserInfo
    /// </summary>
    [Serializable]
    public class UserInfo
    {
        public int UserId { get; set; } // UserId (Primary key)
        public SexType? SexType { get; set; } // SexType
        public EducationType? EducationType { get; set; } // EducationType
    }

}
// </auto-generated>
