// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// UserCourseType
    /// </summary>
    public class UserCourseTypeMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UserCourseType>
    {
        public UserCourseTypeMap()
            : this("curriculum")
        {
        }

        public UserCourseTypeMap(string schema)
        {
            ToTable("UserCourseType", schema);
            HasKey(x => new { x.UserId, x.CourseTypeId });

            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CourseTypeId).HasColumnName(@"CourseTypeId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("bigint").IsRequired();

            // Foreign keys
            HasRequired(a => a.CourseType).WithMany(b => b.UserCourseTypes).HasForeignKey(c => c.CourseTypeId).WillCascadeOnDelete(false); // FK_UserCourseType_CourseType
        }
    }

}
// </auto-generated>
