// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// UserCourseSubject
    /// </summary>
    [Serializable]
    public class UserCourseSubject
    {
        public int UserId { get; set; } // UserId (Primary key)
        public int CourseSubjectId { get; set; } // CourseSubjectId (Primary key)
        public Status Status { get; set; } // Status
    }

}
// </auto-generated>
