// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// UserCourseSubject
    /// </summary>
    public class UserCourseSubjectMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UserCourseSubject>
    {
        public UserCourseSubjectMap()
            : this("curriculum")
        {
        }

        public UserCourseSubjectMap(string schema)
        {
            ToTable("UserCourseSubject", schema);
            HasKey(x => new { x.UserId, x.CourseSubjectId });

            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CourseSubjectId).HasColumnName(@"CourseSubjectId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("bigint").IsRequired();
        }
    }

}
// </auto-generated>
