// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// UserCourseType
    /// </summary>
    [Serializable]
    public class UserCourseType
    {
        public int UserId { get; set; } // UserId (Primary key)
        public int CourseTypeId { get; set; } // CourseTypeId (Primary key)
        public Status Status { get; set; } // Status

        // Foreign keys

        /// <summary>
        /// Parent CourseType pointed by [UserCourseType].([CourseTypeId]) (FK_UserCourseType_CourseType)
        /// </summary>
        public virtual CourseType CourseType { get; set; } // FK_UserCourseType_CourseType
    }

}
// </auto-generated>
