// <auto-generated>
using Lks.Enum;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace Lks.Api.Icas.Entity
{

    /// <summary>
    /// UserInfo
    /// </summary>
    public class UserInfoMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UserInfo>
    {
        public UserInfoMap()
            : this("user")
        {
        }

        public UserInfoMap(string schema)
        {
            ToTable("UserInfo", schema);
            HasKey(x => x.UserId);

            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SexType).HasColumnName(@"SexType").HasColumnType("bigint").IsOptional();
            Property(x => x.EducationType).HasColumnName(@"EducationType").HasColumnType("bigint").IsOptional();
        }
    }

}
// </auto-generated>
